#リストを宣言する
n=[5,2,-3,1]
#リストの値を表示する
print("n[0]={}".format(n[0]))
print("n[1]={}".format(n[1]))
print("n[2]={}".format(n[2]))
print("n[3]={}".format(n[3]))
#リスト全体を表示する
print(n)
#値の一部を変更する
n[1]=6
#再びリスト全体を表示する
print(n)