#２つの集合を定義
fruit1={"りんご","バナナ","パイナップル","グレープフルーツ"}
fruit2={"みかん","りんご","バナナ","オレンジ"}
#和集合
print("和集合")
print(fruit1|fruit2)
print("積集合")
print(fruit1&fruit2)
print("差集合")
print(fruit1-fruit2)
print("対象差")
print(fruit1^fruit2)
